/* tslint:disable */
/* eslint-disable */
/**
 * Speedruns - OpenAPI 3.0
 * Api für den vertikalen Prototypen
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Category = {
    AnyPercent: 'ANY_PERCENT',
    AnyPercentGlitchless: 'ANY_PERCENT_GLITCHLESS',
    AllArchievments: 'ALL_ARCHIEVMENTS',
    AllAdvancements: 'ALL_ADVANCEMENTS'
} as const;
export type Category = typeof Category[keyof typeof Category];


export function instanceOfCategory(value: any): boolean {
    for (const key in Category) {
        if (Object.prototype.hasOwnProperty.call(Category, key)) {
            if (Category[key as keyof typeof Category] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

// @ts-ignore
export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    return json as Category;
}

export function CategoryToJSON(value?: Category | null): any {
    return value as any;
}

// @ts-ignore
export function CategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): Category {
    return value as Category;
}

