/* tslint:disable */
/* eslint-disable */
/**
 * Speedruns - OpenAPI 3.0
 * Api für den vertikalen Prototypen
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Runtime } from './Runtime.ts';
import {
    RuntimeFromJSON,
    RuntimeToJSON,
} from './Runtime.ts';

/**
 * 
 * @export
 * @interface Entry
 */
export interface Entry {
    /**
     * name des Speedrunneraccounts, erstmal Platzhalter, später ist hier auch einen Enittät
     * @type {string}
     * @memberof Entry
     */
    speedrunner: string;
    /**
     * 
     * @type {Date}
     * @memberof Entry
     */
    date: Date;
    /**
     * 
     * @type {Runtime}
     * @memberof Entry
     */
    runtime: Runtime;
}

/**
 * Check if a given object implements the Entry interface.
 */
export function instanceOfEntry(value: object): value is Entry {
    if (!('speedrunner' in value) || value['speedrunner'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('runtime' in value) || value['runtime'] === undefined) return false;
    return true;
}

export function EntryFromJSON(json: any): Entry {
    return EntryFromJSONTyped(json, false);
}

// @ts-ignore
export function EntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entry {
    if (json == null) {
        return json;
    }
    return {
        
        'speedrunner': json['speedrunner'],
        'date': (new Date(json['date'])),
        'runtime': RuntimeFromJSON(json['runtime']),
    };
}

export function EntryToJSON(json: any): Entry {
    return EntryToJSONTyped(json, false);
}

// @ts-ignore
export function EntryToJSONTyped(value?: Entry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'speedrunner': value['speedrunner'],
        'date': ((value['date']).toISOString()),
        'runtime': RuntimeToJSON(value['runtime']),
    };
}

