/* tslint:disable */
/* eslint-disable */
/**
 * Speedruns - OpenAPI 3.0
 * Api für den vertikalen Prototypen
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface Runtime
 */
export interface Runtime {
    /**
     * 
     * @type {number}
     * @memberof Runtime
     */
    hours: number;
    /**
     * 
     * @type {number}
     * @memberof Runtime
     */
    minutes: number;
    /**
     * 
     * @type {number}
     * @memberof Runtime
     */
    seconds: number;
    /**
     * 
     * @type {number}
     * @memberof Runtime
     */
    milliseconds: number;
}

/**
 * Check if a given object implements the Runtime interface.
 */
export function instanceOfRuntime(value: object): value is Runtime {
    if (!('hours' in value) || value['hours'] === undefined) return false;
    if (!('minutes' in value) || value['minutes'] === undefined) return false;
    if (!('seconds' in value) || value['seconds'] === undefined) return false;
    if (!('milliseconds' in value) || value['milliseconds'] === undefined) return false;
    return true;
}

export function RuntimeFromJSON(json: any): Runtime {
    return RuntimeFromJSONTyped(json, false);
}

// @ts-ignore
export function RuntimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Runtime {
    if (json == null) {
        return json;
    }
    return {
        
        'hours': json['hours'],
        'minutes': json['minutes'],
        'seconds': json['seconds'],
        'milliseconds': json['milliseconds'],
    };
}

export function RuntimeToJSON(json: any): Runtime {
    return RuntimeToJSONTyped(json, false);
}

// @ts-ignore
export function RuntimeToJSONTyped(value?: Runtime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hours': value['hours'],
        'minutes': value['minutes'],
        'seconds': value['seconds'],
        'milliseconds': value['milliseconds'],
    };
}

