/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rest/api/games/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all available games.
         * @description Get all available games.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns all available games. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/games/{gameSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game by game slug.
         * @description Get game by game slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameSlug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the GameDto for the given game slug. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameDto"];
                    };
                };
                /** @description Returned if the game slug were not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/games/{gameSlug}/{categoryId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get leaderboard by game slug and category.
         * @description Get leaderboard by game slug and category. The leaderboard is already sorted by runtime.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the game of the leaderboard */
                    gameSlug: string;
                    /** @description the category of the leaderboard */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns a sorted list of runs that are representing the leaderboard. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunDto"][];
                    };
                };
                /** @description Returned if the game slug or category were not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Submit a new run by game and category.
         * @description Submit a new run by game and category.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description the game of the leaderboard */
                    gameSlug: string;
                    /** @description the category of the leaderboard */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RunSubmit"];
                };
            };
            responses: {
                /** @description Returned if the run is submitted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the game slug, category or Speedrunner username were not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the speedrunner already has a faster run time on the leaderboard */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the runtime doesn’t fulfill the requirements. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/runs/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletes an existing run by uuid.
         * @description Deletes an existing run by uuid. Only users with admin rights are allowed to delete a run.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description uuid of the game */
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returned if the run is successfully deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the uuid is not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/games/{gameSlug}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available categories by game slug.
         * @description Get available categories by game slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameSlug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns all available categories for the given game slug. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
                /** @description Returned if the game slug were not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Adds a new category for a game.
         * @description Adds a new category for a game. The id has to be unique. Only users with admin rights are allowed to add a new category.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameSlug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            responses: {
                /** @description Returned if the category was successfully added. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the id is not unique. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/games/{gameSlug}/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletes an existing category for a game.
         * @description Deletes an existing category for a game. The id has to exist. Only users with admin rights are allowed to delete a category.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameSlug: string;
                    /** @description the category of the leaderboard */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returned if the category was successfully deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the id is not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/reviews/unreviewed/{gameSlug}/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of unreviewed runs by game and category.
         * @description Get a list of unreviewed runs. Only users with admin rights are allowed to get all unreviewed runs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameSlug: string;
                    /** @description the category of the leaderboard */
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns a list of all unreviewed runs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunReview"][];
                    };
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/api/reviews/unreviewed/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletes a unreviewed run.
         * @description Deletes a unreviewed run. Only users with admin rights are allowed to delete a run.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description uuid of the game */
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returned if the run is successfully deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the uuid is not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Verifies a unreviewed run.
         * @description Verifies a unreviewed run. Only users with admin rights are allowed to verify a run.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description uuid of the game */
                    uuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returned if the run is successfully verified. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the uuid is not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/rest/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * user login info
         * @description Returns information about the currently authenticated user's token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the authorities if the caller is authenticated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * user login
         * @description Creates a new token for a user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginCredentials"];
                };
            };
            responses: {
                /** @description Returns information about the caller's token if the caller is authenticated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Returned if the login fails due to invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * user registration
         * @description Registers a new user in the system.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterCredentials"];
                };
            };
            responses: {
                /** @description Returned if the user was successfully registered. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Returned if the user is already registered. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterError"];
                    };
                };
                /** @description Returned if the password, email or username doesn’t fulfill the requirements. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/rss/getFeedUrl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the RSS Feed URL.
         * @description Get the RSS Feed URL.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the RSS Feed URL if the caller is authenticated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Returned if the caller is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest/rss/getFeed/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the RSS Feed.
         * @description Get the RSS Feed to the given id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the RSS Feed to the given id. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/xml": string;
                    };
                };
                /** @description Returned if the id is not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RunDto: {
            uuid: string;
            /** @description Username of the speedrunner's account. */
            speedrunner: string;
            /** Format: date-time */
            date: string;
            runtime: components["schemas"]["Runtime"];
            /** Format: URL */
            videoLink: string;
        };
        GameDto: {
            /** @example minecraft */
            name: string;
            slug: string;
            imageUrl: string;
        };
        RunReview: {
            gameName: string;
            categoryLabel: string;
            run: components["schemas"]["RunDto"];
        };
        RunSubmit: {
            /** Format: date-time */
            date: string;
            runtime: components["schemas"]["Runtime"];
            /** Format: URL */
            videoLink: string;
        };
        Category: {
            /** @example ANY_PERCENT */
            categoryId: string;
            /** @example Any % */
            label: string;
        };
        Runtime: {
            hours: number;
            minutes: number;
            seconds: number;
            milliseconds: number;
        };
        TokenResponse: {
            accessToken: string;
            /** @example Bearer */
            tokenType?: string;
            /** @example 3600 */
            expiresIn?: number;
        };
        RegisterError: {
            usernameError?: string;
            emailError?: string;
            passwordError?: string;
        };
        RegisterCredentials: {
            username: string;
            /** Format: password */
            password: string;
            /** Format: email */
            email: string;
        };
        LoginCredentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
