name: Docker Image CI Feature Branch

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches-ignore:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      - name: Generate sanitized subdomain and Docker tag
        id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')
          echo "SUBDOMAIN=${SAFE_BRANCH}.dev.${{ vars.ROOT_DOMAIN }}" >> $GITHUB_ENV
          echo "TAG=${{ vars.DOCKER_HUB_USERNAME }}/se2p-frontend:${SAFE_BRANCH}-$(date +%s)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAG }}
          build-args: |
            BUILD_CLOUDRON_APP_DOMAIN=${{ env.SUBDOMAIN }}
            BUILD_UMAMI_WEBSITE_ID=${{ vars.UMAMI_WEBSITE_ID_STAGING }}
          outputs: type=docker

      - name: Deploy to Cloudron
        uses: rossmaclean/cloudron-deploy-action@v0.0.26
        with:
          app-domain: ${{ env.SUBDOMAIN }}
          image: ${{ env.TAG }}
          cloudron-server: ${{ vars.CLOUDRON_SERVER }}
          cloudron-token: ${{ secrets.CLOUDRON_API_TOKEN }}
          install-if-missing: "true"
