name: Docker Image CI

on:
  release:
    types: ["published"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}
      - name: Generate Docker tag
        id: tag
        run: echo "TAG=${{ vars.DOCKER_HUB_USERNAME }}/se2p-frontend:$(date +%s)" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAG }}
          build-args: |
            BUILD_CLOUDRON_APP_DOMAIN=${{ vars.CLOUDRON_APP_DOMAIN }}
            BUILD_UMAMI_WEBSITE_ID=${{ vars.UMAMI_WEBSITE_ID }}
      - name: Deploy on Cloudron
        uses: rossmaclean/cloudron-deploy-action@v0.0.26
        with: 
          app-domain: ${{ vars.CLOUDRON_APP_DOMAIN }}
          image: ${{ env.TAG }}
          cloudron-server: ${{ vars.CLOUDRON_SERVER }}
          cloudron-token: ${{ secrets.CLOUDRON_API_TOKEN }}
          install-if-missing: "true"
